#
# Makefile for the fingerprint drivers.
#

ccflags-$(CONFIG_FINGERPRINT_FPS998E_ZQL1606_ID_HI) += -DSUPPORT_FP_ID_DUAL -DFP_ID_VALUE=1
ccflags-$(CONFIG_FINGERPRINT_FPS998E_ZQL1606_ID_LO) += -DSUPPORT_FP_ID_DUAL -DFP_ID_VALUE=0

obj-y += cdfingerfp.o
