#
## Makefile for the touchscreen drivers.
#
#
## Each configuration option enables a list of files.
ccflags-y += -I$(srctree)/drivers/input/touchscreen/lge/

obj-$(CONFIG_LGE_TOUCH_FOCALTECH_FT8736)         += touch_ft8736.o
obj-$(CONFIG_LGE_TOUCH_FOCALTECH_FT8736)         += touch_ft8736_prd.o